### ISSUE TITLE
codelens not displayed after oppening file

### ISSUE THREAD

**Issue by mateusz834** [ray-x/go.nvim#183]
When I open file from cli nvim file.go the codelens are displayed only after "i\<ESC\>" and all files opened in additional buffers (via :edit, telescope) don't have codelens even after  "i\<ESC\>".

**Comment by mateusz834** [comment]
when i specify lsp_on_attach, then even at the first file open the codelens are not shown.

**Comment by ray-x** [comment]
I pushed an update for this, could you check if it works for you?

**Comment by mateusz834** [comment]
I have no idea I changed something yesterday and ccodelens stopped working, even after this change they are still not displayed for me
```
local golspcfg = {                                                                                
    settings = {                                                                                  
        gopls = {                                                                                 
            analyses = {                                                                          
                fieldalignment = true,                                                            
                nilness = true,                                                                   
                unusedwrite = true,                                                               
                useany = true,                                                                    
                unusedparams = true,                                                              
                shadow = true,                                                                    
            },                                                                                    
            staticcheck = true,                                                                   
        },                                                                                        
    },                                                                                            
}                                                                                                 
                                                                                                  
require('go').setup({                                                                             
    gofmt="gofmt",                                                                                
    lsp_cfg = golspcfg,-                                                                          
    lsp_inlay_hints = {                                                                           
        parameter_hints_prefix='#',                                                               
    },                                                                                            
    lsp_on_attach = function (client, bufnr)-                                                     
        require('config.keymap').go_on_attach(client, bufnr)                                      
        require('lsp_signature').on_attach()                                                      
    end,                                                                                          
    lsp_keymaps = false,                                                                          
}) 
```

**Comment by aphasia51** [comment]
> 

I have the same problem. After getting back to the go.nvim version, I solved it

**Comment by mateusz834** [comment]
codelens are working, but on the second buffer (not on first one)

**Comment by mateusz834** [comment]
```
Executing BufEnter Autocommands for "*.go"
autocommand <lua: 14>

Error detected while processing BufEnter Autocommands for "*.go":
method textDocument/codeLens is not supported by any of the servers registered for the current buffer
Executing BufEnter Autocommands for "*.go"
autocommand <lua: 18>
```

**Comment by ray-x** [comment]
Was gopls ready when codeLens request was sent?

**Comment by ray-x** [comment]
Ok, I think the error message you saw is because `BufEnter` autocmd will send codelens requests. There is a chance gopls is not read when BufEnter is triggered if you are not lazyloading go.nvim.
I removed the BufEnter hook. You should not see the error again.

**Comment by mateusz834** [comment]
Now it works, but there is still the same issue, to see codelens on the first buffer I need to 'i<ESC>'.

**Comment by mateusz834** [comment]
Maybe the LspAttach event could be used to fix that? https://neovim.io/doc/user/lsp.html#lsp-events

**Comment by ray-x** [comment]
codelens is slow (2~4s depends on your project size) and it is triggered by cursor hold, not bufenter.

**Comment by mateusz834** [comment]
or just, by adding  `vim.lsp.codelens.refresh()` to on_attach.
```
require('go').setup({
    gofmt="gofmt",
    lsp_cfg = golspcfg,
    lsp_inlay_hints = {
        parameter_hints_prefix='#',
    },
    lsp_on_client_start = function (client, bufnr)
        require('config.keymap').go_on_attach(client, bufnr)
        require('lsp_signature').on_attach()
        vim.lsp.codelens.refresh()
    end,
    lsp_keymaps = false,
})
```

**Comment by ray-x** [comment]
As I mentioned. using the minimum from go.nvim/playground/init.lua

https://user-images.githubusercontent.com/1681295/182023700-a9e97640-abfa-4b71-ad24-6a74a65d30c5.mp4

I added vim.lsp.codelens.refresh() in on_attach() either way as it may save a few hundred millisecond.

**Comment by lijinglin3** [comment]
after pull latest commit, codelen works fine but opening buffer for the first time shows the following error

```
Error detected while processing InsertLeave Autocommands for "*.go":
method textDocument/codeLens is not supported by any of the servers registered for the current buffer
Press ENTER or type command to continue
```

**Comment by ray-x** [comment]
Could this reproduce with `go.nvim/playground/init.lua`

**Comment by lijinglin3** [comment]
> Could this reproduce with `go.nvim/playground/init.lua`

cannot be reproduced, but show following error after nvim quit

```
Client 1 quit with exit code 2 and signal 0
```

**Comment by lijinglin3** [comment]
> after pull latest commit, codelen works fine but opening buffer for the first time shows the following error
> 
> ```
> Error detected while processing InsertLeave Autocommands for "*.go":
> method textDocument/codeLens is not supported by any of the servers registered for the current buffer
> Press ENTER or type command to continue
> ```

After testing, it only occurs when the file is opened with telescope.find_files

**Comment by ray-x** [comment]
Not sure why would this happen. But I pushed a gopls check for this. Could you check if it works?

**Comment by lijinglin3** [comment]
> Not sure why would this happen. But I pushed a gopls check for this. Could you check if it works?

It's working fine, thanks
