### ISSUE TITLE
E5108 when running goRun, or GoBuild

### ISSUE THREAD

**Issue by ezraclintoc** [ray-x/go.nvim#596]
When running "GoRun" or "GoBuild" I get an error

E5108: Error executing lua ...ra/.local/share/nvim/lazy/guihua.lua/lua/guihua/util.lua:248: attempt to call field 'ft_to_lang' (a nil value)
stack traceback:
	...ra/.local/share/nvim/lazy/guihua.lua/lua/guihua/util.lua:248: in function 'highlighter'
	.../.local/share/nvim/lazy/guihua.lua/lua/guihua/sprite.lua:126: in function 'initialize'
	...ra/.local/share/nvim/lazy/guihua.lua/lua/middleclass.lua:181: in function 'new'
	...ezra/.local/share/nvim/lazy/go.nvim/lua/go/asyncmake.lua:210: in function 'make'
	[string ":lua"]:1: in main chunk

**Comment by Vadim-Maklakov** [comment]
I'll raise the topic and support the author because I'm experiencing the same error.
Hi all! 
I want using LazyVim as Golang/Python/SQL IDE. I have next host software configuration:
NVIM v0.11.4
LuaJIT 2.1.1741730670
lazy.nvim  11.17.2
OS: Debian GNU/Linux 12 (bookworm)
Kernel: 6.1.0-17-amd64
Go: `go version go1.25.0 linux/amd64`
and setup LazyVim folke configuration from https://www.lazyvim.org/.

I installed LazyVim using two steps:
Step 1. Add to plugins directory custom  nvim-treesitter.lua and mason-nvim.lua containing custom language parsers, LSP, DAP, Linters and formatters using lingks LazyVim for Go, Python and SQL and other languages.
Step 2. Exit from LazyVim after Step 1, add to plugins directory standard  go-xray.lua contain standard setting for lazy.nvim from https://github.com/ray-x/go.nvim.

I install ray-x/go.nvim before and after installing go from LazyExtras. In other cases when I run checkhealth after installing ray-x/go.nvim I got same results:

```
Go Plugin Check ~
- ✅ OK lspconfig: plugin is installed
- ✅ OK nvim-treesitter: plugin is installed
- ✅ OK guihua: plugin is installed
- ✅ OK nvim-dap-virtual-text: plugin is installed
- ⚠️ WARNING telescope: not installed/loaded
- ❌ ERROR Failed to run healthcheck for "go" plugin. Exception:
  /home/mvg/.local/share/nvim/lazy/go.nvim/lua/go/health.lua:151: module 'nvim-treesitter.info' not found:
  	no field package.preload['nvim-treesitter.info']
  	cache_loader: module 'nvim-treesitter.info' not found
  	cache_loader_lib: module 'nvim-treesitter.info' not found
  	no file './nvim-treesitter/info.lua'
  	no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1/nvim-treesitter/info.lua'
  	no file '/usr/local/share/lua/5.1/nvim-treesitter/info.lua'
  	no file '/usr/local/share/lua/5.1/nvim-treesitter/info/init.lua'
  	no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/nvim-treesitter/info.lua'
  	no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/nvim-treesitter/info/init.lua'
  	no file '/home/mvg/.local/share/nvim/lazy-rocks/nvim-dap-python/share/lua/5.1/nvim-treesitter/info.lua'
  	no file '/home/mvg/.local/share/nvim/lazy-rocks/nvim-dap-python/share/lua/5.1/nvim-treesitter/info/init.lua'
  	no file './nvim-treesitter/info.so'
  	no file '/usr/local/lib/lua/5.1/nvim-treesitter/info.so'
  	no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/nvim-treesitter/info.so'
  	no file '/usr/local/lib/lua/5.1/loadall.so'
  	no file '/home/mvg/.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/fuzzy/rust/../../../../../target/release/libnvim-treesitter/info.so'
  	no file '/home/mvg/.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/fuzzy/rust/../../../../../target/release/nvim-treesitter/info.so'
  	no file '/home/mvg/.local/share/nvim/lazy-rocks/nvim-dap-python/lib/lua/5.1/nvim-treesitter/info.so'
  	no file '/home/mvg/.local/share/nvim/lazy-rocks/nvim-dap-python/lib64/lua/5.1/nvim-treesitter/info.so'
  	no file './nvim-treesitter.so'
  	no file '/usr/local/lib/lua/5.1/nvim-treesitter.so'
  	no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/nvim-treesitter.so'
  	no file '/usr/local/lib/lua/5.1/loadall.so'
  	no file '/home/mvg/.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/fuzzy/rust/../../../../../target/release/libnvim-treesitter.so'
  	no file '/home/mvg/.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/fuzzy/rust/../../../../../target/release/nvim-treesitter.so'
  	no file '/home/mvg/.local/share/nvim/lazy-rocks/nvim-dap-python/lib/lua/5.1/nvim-treesitter.so'
  	no file '/home/mvg/.local/share/nvim/lazy-rocks/nvim-dap-python/lib64/lua/5.1/nvim-treesitter.so'

```
After installing  ray-x/go.nvim I get errors when I tried executing next it commands GoBuild (`GoBuild_Error.txt`), GoRun (`GoRun_Error.txt`), GoCheat(`GoCheat_Error.txt`), GoClearTag(`GoClearTag_Error.txt`), GoCmt(`GoCmt_error.txt`). Text files contains detailed information about errors.
 
Errors reproduced on lazy.nvim  11.17.2 and NVIM v0.11.4 on Windows 10 host.
But when I installed AstroNvim https://docs.astronvim.com/ which using same version  lazy.nvim  11.17.2 and install ray-x/go.nvim all Go problems commands above working correctly. But AstroNvim have poor Go LSP than  LazyVim folke with Go installed with LazyExtras. 

More detailed information see in  the attachment files.

[lua.tar.gz](https://github.com/user-attachments/files/23151885/lua.tar.gz)

[checkhealt-lazyvim-org-before-x-ray-goplugin-v11.17.2.txt](https://github.com/user-attachments/files/23151897/checkhealt-lazyvim-org-before-x-ray-goplugin-v11.17.2.txt)
[checkhealt-lazyvim-org-with-x-ray-goplugin-v11.17.2.txt](https://github.com/user-attachments/files/23151891/checkhealt-lazyvim-org-with-x-ray-goplugin-v11.17.2.txt)
[GoBuild_Error.txt](https://github.com/user-attachments/files/23151892/GoBuild_Error.txt)
[GoCheat_Error.txt](https://github.com/user-attachments/files/23151899/GoCheat_Error.txt)
[GoClearTag_Error.txt](https://github.com/user-attachments/files/23151895/GoClearTag_Error.txt)
[GoCmt_error.txt](https://github.com/user-attachments/files/23151896/GoCmt_error.txt)
[GoRun_Error.txt](https://github.com/user-attachments/files/23151898/GoRun_Error.txt)
[Lazy-Extras-status.txt](https://github.com/user-attachments/files/23151893/Lazy-Extras-status.txt)
[lazy-lock.json](https://github.com/user-attachments/files/23151894/lazy-lock.json)
[Lazy-status.txt](https://github.com/user-attachments/files/23151900/Lazy-status.txt)
[lazyvim.json](https://github.com/user-attachments/files/23151890/lazyvim.json)

**Comment by ray-x** [comment]
Assuming you're on the treesitter-main branch, I've pushed a fix to guihua.lua. Please pull the changes and let me know if this resolves the issue. 
We can track any remaining issues related to the treesitter-main branch here: https://github.com/ray-x/go.nvim/issues/576.

**Comment by greg0ire** [comment]
@ray-x I was experiencing the issue as well, and yes, your push fixes it. Many thanks for this fix, and for this plugin!

**Comment by ezraclintoc** [comment]
I am still having this issue. I have updated everything in nvim with Lazy's update command. By pull, do you mean I have to pull the actual code?
