### ISSUE TITLE
Need help with :GoDebug and keybindings for dlv and dap

### ISSUE THREAD

**Issue by rodrigc** [ray-x/go.nvim#71]
I need some help with how to use the DAP integration for debugging.

## Setup
* Default setup: https://github.com/rodrigc/neovim-setup/tree/main/.config/nvim
* Init: https://github.com/rodrigc/neovim-setup/blob/main/.config/nvim/init.lua
* dap plugins: https://github.com/rodrigc/neovim-setup/blob/main/.config/nvim/lua/plugins.lua#L76
* go setup:  https://github.com/rodrigc/neovim-setup/blob/main/.config/nvim/lua/config/go.lua

## Steps to try
1.  Opened a go fie in the editor
2.  Positioned my cursor in the main() function
3.  Ran `:GoDebug`
4.  DAP started and opened a bunch of windows
5.  Run `:GoBreakToggle`
6.  How do I use the default keybindings, `n`, `s`, `c` as listed here: https://github.com/ray-x/go.nvim/blob/master/lua/go/dap.lua#L25

Those didn't seem to work for me.

**Comment by ray-x** [comment]
You may need to set break point first with `:GoBreakToggle`
So the step should be 1, 2, 5, 3, 4, 6

**Comment by rodrigc** [comment]
I tried running the steps in order 1, 2, 5, 3, 4, 6
and it didn't work for me.

The different DAP windows appeared,
but pressing `n`, `s`, `c` didn't work for me.

Are there some other steps or config that I need to set up?

**Comment by ray-x** [comment]
May need to turn on `  dap_debug_keymap = true,` in your setup. For some reason, it defaults to be false. I pushed an update to fix that.

**Comment by rodrigc** [comment]
With latest go.nvim, I tried the following:

1.  Open go file with `main()` function
2. Use `:GoBreakToggle` to set breakpoint in `main()`
3.  Run `:GoDebug`
4.  Press `n` a few times to go to next line (it works)
5.  Press `r`,  *the dap windows seem to get duplicated on the left*

Is this expected behavior?

I then try:

1.  Press `r` again
2.  Now I see:

```
Session active, but not stopped at breakpoint>
1: Terminate session
2: Pause a thread
3: Restart session
4: Disconnect (terminate = true)
5: Disconnect (terminate = false)
6: Do nothing
Type number and <Enter> or click with the mouse (q or empty cancels):
```

3.  I press `1`.  Now the dap windows are triplicated on the left

Is this expected behavior?

**Comment by ray-x** [comment]
When you start debug with GoDebug, it is in `run` state. 
So you should use `c` to continue the run. Or `GoDebug restart` to restart from begining
Both `GoDebug restart` and `GoDebug stop` will clean the state and reset GUI layout.  If run `GoDebug` multiple times you will get more and more debug windows.

**Comment by rodrigc** [comment]
Thanks for https://github.com/ray-x/go.nvim/commit/ca1d46b4ab952c98952e376d9fc19b4cdcc9e487

The behavior is a bit better with that change.  I'm a bit confused though.

If I do:

1.  Open file
2.  `:GoBreakToggle` to set breakpoint in `main()`
3.  `:GoDebug` to start debug
4.   Press `n` a few times to advance
5.  `:GoDebug restart`, I get this:  `debug session already start, press c to continue`
      At this point, I wait a little bit, then press `n` a few more times to advance.
      
      GoDebug session never restarted.  Is this expected?


Right now, to get the behavior that I was expecting, I need to:

1.  Press `S` to stop the debug session
2.  Press `r` to re-run the debug session

**Comment by rodrigc** [comment]
Also, I tried this:

1.  `:GoDebug`
2.  Press `n` a few times
3.  `:GoDebug stop`
4.  I get: `debug session already start, press c to continue`

The GoDebug session never stopped.

Is that expected?

**Comment by ray-x** [comment]
Thanks. the session checker was in the wrong place. should be fixed.

**Comment by rodrigc** [comment]
I updated go.nvim, and now when I do `:GoDebug`, I get this:

```
Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:127: Error: attempted to load guihua.lua which is not present in plugins table!
Please check your config for correctness
WRN: plugin failed to load guihua.lua
```

Is floatterm and guihua now mandatory for GoDebug?

If it is, that's OK, just need to reflect that in the README

**Comment by ray-x** [comment]
It is not mandatory. seems something wrong with packer.loader method. I updated the code and please check if it works.

**Comment by rodrigc** [comment]
With latest patch, I don't get a tracktrace, but if I do `:GoDebug`

I still see:
```
WRN: plugin failed to load guihua.lua
```

That is OK.

One question.  Should `util.warn(), util.error(), util.info()` be changed from using `vim.api.nvim_echo` to `vim.notify` ?

**Comment by ray-x** [comment]
Yes, good idea. updated

**Comment by rodrigc** [comment]
I'm using go.nvim with dap and it is working very well. 👍 

I need to debug two different go binaries on the same host
to debug some complex interactions.

It looks like go.nvim hardcodes the dap port to `127.0.0.1:38697`.
So I cannot start two separate nvim sessions with go.nvim, with the debugger.
I can only start one dap session.

Is there a way I can override port `38697` in one editor session?

**Comment by ray-x** [comment]
I pushed an update so the port can be a random number.
